# Generated by Django 2.2.1 on 2020-03-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reuniones',
            options={'verbose_name': 'Reunión', 'verbose_name_plural': 'Reuniones'},
        ),
    ]
