# Generated by Django 2.2.1 on 2020-03-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=80, verbose_name='Nombre Completo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreGrado', models.CharField(choices=[('Nursery', 'Nursery'), ('Pre-Kinder', 'Pre-Kinder'), ('Kinder', 'Kinder'), ('Parvulos', 'Parvulos'), ('Preprimaria', 'Preprimaria'), ('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto')], default='Primero', max_length=30, verbose_name='Grado')),
                ('Nivel', models.CharField(choices=[('Preprimario', 'Preprimario'), ('Primario', 'Primario'), ('Básico', 'Básico'), ('Bachillerato', 'Bachillerato'), ('PGA', 'PGA')], default='Primario', max_length=30, verbose_name='Nivel')),
                ('Seccion', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Única', 'Única')], default='A', max_length=30, verbose_name='Sección')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=80, verbose_name='Nombre Maestro')),
            ],
            options={
                'verbose_name': 'Maestro',
                'verbose_name_plural': 'Maestros',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('TipoPermiso', models.CharField(choices=[('Escrito', 'Escrito'), ('Llamada', 'Llamada'), ('Ninguno', 'Ninguno')], default='Ninguno', max_length=15, verbose_name='Tipo de Permiso')),
                ('Descripcion', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('NombreAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Alumno', verbose_name='Alumno')),
                ('NombreMaestro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Maestro', verbose_name='Maestro')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asistencia.Grado', verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
    ]
