# Generated by Django 2.2.12 on 2021-01-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='Nivel',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='Seccion',
        ),
    ]
